---
title: "Project 1 Task 3"
format: 
  html:
    code-fold: true
editor: visual
execute: 
  echo: true
  warning: false
---

## 

```{r}
library(data4led)
f0 <- function(x, a0=100){
  return(a0)
}
f1 <- function(x, a1=0.00025830080, a0=100){
  return(a0 + (a1 * x))
}
f2 <- function(x, a1=0.0004842401, a2=-0.00000008834307, a0=100){
  return(a0 + a1 * x + a2 * x^2)
}
f3 <- function(x, a1=-38.96574 , a2=10.57587, a0=100.6203){
  return(a0 + a1 * exp(-a2 * x))
}
f4 <- function(x, a1=-0.0002051946, a2=0.4895432441){
  return(100 + a1 * x + a2 * log((0.005 * x + 1)))
}
f5 <- function(x, a1=0.1497315, a2=0.0004607059, a0=-0.1486081){
  return((a0 + a1 * x) * exp(-a2 * x))
}
```


```{r}
bulb <- led_bulb(1, seed = 719)
```


# Function 0

```{r}
par(mfrow=c(1,2))
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)", xlim = c(0,80000), ylim = c(-10,120))
abline(a = 100, b = 0)  
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)")
abline(a = 100, b = 0)  
par(mfrow=c(1,1))
```


# Function 1

```{r}
par(mfrow=c(1,2))
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)", xlim = c(0,80000), ylim = c(-10,120))
curve(f1, add = TRUE, col = "red")  
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)")
curve(f1, add = TRUE, col = "red")  
par(mfrow=c(1,1))
```

# Function 2

```{r}
par(mfrow=c(1,2))
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)", xlim = c(0,80000), ylim = c(-10,120))
curve(f2, add = TRUE, col = "red") 
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)")
curve(f2, add = TRUE, col = "red")
par(mfrow=c(1,1))
```

# Function 3

```{r}
par(mfrow=c(1,2))
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)", xlim = c(0,80000), ylim = c(-10,120))
curve(f3, add = TRUE, col = "red")  
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)")
curve(f3, add = TRUE, col = "red")  
par(mfrow=c(1,1))
```

# Function 4

```{r}
par(mfrow=c(1,2))
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)", xlim = c(0,80000), ylim = c(-10,120))
curve(f4, add = TRUE, col = "red") 
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)")
curve(f4, add = TRUE, col = "red") 
par(mfrow=c(1,1))
```

# Function 5

```{r}
par(mfrow=c(1,2))
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)", xlim = c(0,80000), ylim = c(-10,120))
curve(f5, add = TRUE, col = "red") 
plot(bulb$hours, bulb$percent_intensity, main = "Bulb Hours and Intensity (%)", xlab = "Hours", ylab = "Intensity(%)")
curve(f5, add = TRUE, col = "red") 
par(mfrow=c(1,1))
```
